create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    credits integer not null default 0 check (credits >= 0)
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    price integer not null check (price >= 0),
    stock integer not null default 0 check (stock >= 0)
);

insert into public.users (id, name, credits)
values
    (1, 'Mario', 200)
on conflict (id) do nothing;

insert into public.products (name, price, stock)
values
    ('Mouse Gaming', 50, 5),
    ('Tastiera RGB', 80, 3),
    ('Cuffie Studio', 120, 2)
on conflict do nothing;
