create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique,
    password_hash text not null,
    role text not null default 'customer' check (role in ('customer', 'admin')),
    credits integer not null default 0 check (credits >= 0),
    created_at timestamptz not null default now()
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text not null default '',
    category text not null default 'Tech',
    image_url text,
    price integer not null check (price >= 0),
    discount_percent integer not null default 0 check (discount_percent >= 0 and discount_percent <= 90),
    stock integer not null default 0 check (stock >= 0),
    created_at timestamptz not null default now()
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    total integer not null check (total >= 0),
    status text not null default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
    created_at timestamptz not null default now()
);

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete restrict,
    quantity integer not null check (quantity > 0),
    unit_price integer not null check (unit_price >= 0)
);

create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete cascade,
    rating integer not null check (rating >= 1 and rating <= 5),
    comment text not null default '',
    created_at timestamptz not null default now()
);

insert into public.users (name, email, password_hash, role, credits)
values
    ('Admin', 'admin@ecommerce.local', '$2a$10$dbsCsySazhmw1SF5A.GEW..oSkiT58v..Ac/VAcruYfilIIUWAZRO', 'admin', 10000),
    ('Mario', 'mario@customer.local', '$2a$10$a8a.dv25pm8YzqR0lWyiHu9gNNQRzutLF0gVOUgAESCE.Tf4Pdnjq', 'customer', 1200)
on conflict (email) do nothing;

insert into public.products (name, description, category, image_url, price, discount_percent, stock)
values
    (
        'Mouse Gaming Pro',
        'Mouse ergonomico RGB ad alta precisione per gaming competitivo.',
        'Periferiche',
        'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80',
        85,
        10,
        24
    ),
    (
        'Tastiera RGB Meccanica',
        'Tastiera meccanica full-size con switch lineari e layout ITA.',
        'Periferiche',
        'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=900&q=80',
        149,
        15,
        15
    ),
    (
        'Cuffie Studio ANC',
        'Cuffie over-ear con cancellazione rumore e audio bilanciato.',
        'Audio',
        'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
        220,
        20,
        12
    ),
    (
        'Laptop Creator 16',
        'Laptop 16 pollici ad alte prestazioni per sviluppo e content creation.',
        'Laptop',
        'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',
        1890,
        8,
        8
    )
on conflict (name) do nothing;
